In [12]:
import torch
import math
from utils import *
from nn import *

%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
train_input, train_target = generate_disc_data()
test_input, test_target = generate_disc_data()

In [14]:
model = Sequential(Linear(2,10),
                   ReLU(),
                   Linear(10,1),
                   Tanh())


In [28]:
out = model.backward(torch.ones((10,1)))

(tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]),)
(tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),)
(tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),)


IndexError: The shape of the mask [10, 10] at index 1 does not match the shape of the indexed tensor [10, 1] at index 1